name: Run Unity Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build python3 python3-pip
          pip3 install meson

      - name: Configure project
        run: meson setup build

      - name: Compile
        run: meson compile -C build

      - name: Run tests
        run: meson test -C build --print-errorlogs
